apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app: {{ template "fullname" . }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: "unbound"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
          - name: "dns"
            containerPort: 53
            protocol: "UDP"
          volumeMounts:
          - name: "unbound-conf"
            mountPath: "/etc/unbound/" #TODO this may need the filename, but it originally didn't have it
            readOnly: true
          # livenessProbe:
          #   exec:
          #     command:
          #       - "nslookup"
          #       - "health.check.unbound"
          #       - "127.0.0.1"
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 2
          # readinessProbe:
          #   exec:
          #     command:
          #       - "nslookup"
          #       - "health.check.unbound"
          #       - "127.0.0.1"
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 2
      volumes:
      - name: "unbound-conf"
        configMap:
          name: "unbound-conf"
