apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ template "fullname" . }}
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: dns
